deployment:
      tasks:
        - export DEPLOYPATH=/home/magyaro3/public_html    # Add /<app_folder> if required
        - /bin/cp index.php $DEPLOYPATH
  	- /bin/cp -a * $DEPLOYPATH
        - /bin cp * $DEPLOYPATH                           #copy all from root 
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH